# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Adiradjapin
email: adiradjapin@gmail.com
tagline: BAHAN BAKU PIN and MATERIAL PIN
description: >- # this means to ignore newlines until "baseurl:"
  Kami adalah produsen souvenir dan merchandise, 
  kami menawarkan harga yang terjangkau dengan kualitas terbaik. 
  Kami memproduksi PIN dan gantungan kunci. 
  Selain itu kami juga memproduksi MUG, Pakaian serta 
  berbagai souvenir &amp; merchandise lainnya.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: adiradjapin
instagram_username:  adiradjapin

# Author
author: Boed Winangun
twitter_author: boedwinangun

# Build settings
markdown: kramdown
theme: minima

port: 8000

sass:
  sass_dir: assets/css
  style: :compressed

plugins:
  - jekyll-feed

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
